# edge lines, line category:
# {
#     'concave_wall_line': 0,
#     'convex_wall_line': 1,
#     'wall_ground_line': 2,
#     'cabinet_wall_line': 3,
#     'cabinet_ground_line': 4,
#     'sofa_ground_line': 5,
#     'stair_line': 6,
#     'ceiling_line': 7,
#     'wall_ground_curve': 8,
#     'stair_curve': 9,
#     'cabinet_ground_curve': 10,
#     'sofa_ground_curve': 11
# }
Line[] lines

# wall corners
Keypoint[] corners